### ISSUE TITLE
confirmation email to grad school

### ISSUE THREAD

**Issue by tibbben** [UMiamiLibraries/sword-deposit#31]

**Comment by tibbben** [comment]
copied to admins as well

**Comment by cgb37** [comment]
charles opened ticket on feb 1, 2021 to whitelist smtp
https://umiami.service-now.com/nav_to.do?uri=incident.do?sys_id=cc065b351b466c50a1fcc9176e4bcb48%26sysparm_view=ess

**Comment by cgb37** [comment]
single email to student and array of admins

**Comment by cgb37** [comment]
A new thesis/dissertation for Open Access Dissertations has been uploaded by "student name" <email>.
 
The authors are:
"student name" <email>
The title is:
"a great title"
 
The keywords are:
keywords; rain;snow;air
