### ISSUE TITLE
Refactor zip filename creation

### ISSUE THREAD

**Issue by cgb37** [UMiamiLibraries/sword-deposit#45]
When a filename is too long the submission fails.

**Comment by tibbben** [comment]
simply set a limit to the filename that is created, the title length should not matter in the end.

**Comment by cgb37** [comment]
we should check with espoloro and make sure they're not using varchar for the title field. it's max is 255. anything larger needs to be a TEXT type field

**Comment by enprieto** [comment]
deployed to enp-hotfix
