### ISSUE TITLE
validate for copy and paste formatted abstract??

### ISSUE THREAD

**Issue by tibbben** [UMiamiLibraries/sword-deposit#49]

**Comment by tibbben** [comment]
remove Microsoft word tags

**Comment by tibbben** [comment]
make character limit 1800

**Comment by tibbben** [comment]
white list for subscript, superscript, italics tags, see https://ckeditor.com/docs/ckeditor5/latest/examples/builds/document-editor.html

**Comment by enprieto** [comment]
ckeditor implemented with 1800 character limit.
